global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'shoestore'
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: "prometheus"
    static_configs:
        - targets: [ "localhost:9090" ]
