global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'shoestore'
    static_configs:
      - targets: ['host.docker.internal:8080']
  
  - job_name: "microservice"
    static_configs:
      - targets: ['host.docker.internal:8081']

  - job_name: "prometheus"
    static_configs:
        - targets: [ "localhost:9090" ]


#  - job_name: "grafana"
#    static_configs:
#        - targets: [ "localhost:3000" ]
#  - job_name: "elasticsearch"
#    static_configs:
#        - targets: [ "localhost:9200" ]
#  - job_name: "kibana"
#    static_configs:
#        - targets: [ "localhost:5601" ]