global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'shoestore'
    static_configs:
      - targets: ['host.docker.internal:8080']
  
  - job_name: "microservice"
    static_configs:
      - targets: ['host.docker.internal:8081']

  - job_name: "prometheus"
    static_configs:
        - targets: [ "localhost:9090" ]
