apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sre-api
  template:
    metadata:
      labels:
        app: sre-api
    spec:
      containers:
      - name: sre-api
        image: sre-api:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "500m"
